name: Build OS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies and cross-compiler
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib g++-multilib nasm wget bison flex

          # Download prebuilt i686-elf toolchain (lordmilko)
          wget https://github.com/lordmilko/i686-elf-tools/releases/download/13.2.0/i686-elf-tools-linux.zip
          unzip i686-elf-tools-linux.zip -d i686-elf-tools
          sudo mv i686-elf-tools /usr/local/i686-elf-tools
          sudo ln -sf /usr/local/i686-elf-tools/bin/* /usr/local/bin/

          # Verify cross-compiler
          i686-elf-gcc --version
          i686-elf-ld --version
          nasm -v

      - name: Build OS
        run: |
          make clean
          make all

      - name: Upload OS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: os-build
          path: ./bin/os.bin