name: Build OS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies and cross-compiler
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib g++-multilib nasm wget bison flex
          
          # Install i686-elf toolchain (cross-compiler + binutils)
          # This is not available via default apt, so build or download prebuilt:
          # Download prebuilt i686-elf toolchain
          wget https://toolchains.bootlin.com/downloads/releases/toolchains/i686-elf/2023.11-1/i686-elf-linux-gnu.tar.xz
          sudo tar -xf i686-elf-linux-gnu.tar.xz -C /usr/local
          sudo ln -sf /usr/local/i686-elf-linux-gnu/bin/* /usr/local/bin/
    
          # Verify cross-compiler works
          i686-elf-gcc --version
          i686-elf-ld --version
          nasm -v

      - name: Build OS
        run: |
          make clean
          make all

      - name: Upload OS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: os-build
          path: ./bin/os.bin