name: Makefile CI

on:
  push:
    paths:
    - 'Makefile'
    - 'build.sh'
    - 'src/**'
    - '.github/workflows/makefile.yml'
  pull_request:
    paths:
    - 'Makefile'
    - 'build.sh'
    - 'src/**'
    - '.github/workflows/makefile.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required tools
      run: |
        sudo apt update
        sudo apt install -y nasm make curl

    - name: Download and install i686-elf toolchain
      run: |
        curl -L https://github.com/lordmilko/i686-elf-tools/releases/download/13.2.0/i686-elf-tools-linux.zip -o i686-elf-tools-linux.zip
        mkdir $HOME/i686-elf-tools
        unzip i686-elf-tools-linux.zip -d $HOME/i686-elf-tools
        echo "$HOME/i686-elf-tools/bin" >> $GITHUB_PATH

    - name: Verify toolchain
      run: |
        i686-elf-gcc --version
        i686-elf-as --version

    - name: Build project
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: os-bin
        path: bin/os.bin
