name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (nasm, make, curl)
      run: |
        sudo apt update
        sudo apt install -y nasm make curl xz-utils

    - name: Download and extract i686-elf GCC toolchain
      run: |
        mkdir -p $HOME/opt
        curl -L https://github.com/xpack-dev-tools/i686-elf-gcc-xpack/releases/download/v12.2.0-2/xpack-i686-elf-gcc-12.2.0-2-linux-x64.tar.gz \
          | tar -xz -C $HOME/opt
        echo "$HOME/opt/xpack-i686-elf-gcc-*/bin" >> $GITHUB_PATH

    - name: Verify toolchain installed
      run: |
        i686-elf-gcc --version
        i686-elf-as --version

    - name: Build project
      run: make

    - name: Run distcheck (if available)
      run: make distcheck

    - name: Prepare output for upload
      run: |
        mkdir -p bin
        cp os.bin bin/os.bin

    - name: Upload OS binary
      uses: actions/upload-artifact@v4
      with:
        name: os-bin
        path: bin/os.bin
